#!/bin/sh

export DBUS_SYSTEM_BUS_ADDRESS=unix:path=/host/run/dbus/system_bus_socket

chmod 777 /data/
chmod 644 /var/spool/cron/root

/etc/init.d/apache2 start
/etc/init.d/crond start

udevd &
udevadm trigger

fbcp &

WPE_BCMRPI_TOUCH=1 WPELauncher $WPE_URL
